services:
  # Serviço do SQL Server
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourPassword123  # Altere para uma senha segura
    ports:
      - "1433:1433"  # Porta padrão do SQL Server
    networks:
      - app-network

  # Serviço da aplicação ASP.NET Core
  pmanage.api:
    image: ${DOCKER_REGISTRY-}pmanageapi
    build:
      context: .
      dockerfile: PManage.API/Dockerfile
    container_name: pmanage-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=ProductDb;User=sa;Password=YourPassword123;
    ports:
      - "5000:80"  # Porta que sua API ficará disponível
    depends_on:
      - sqlserver
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
